// all types of action names exported

export const COLLEGE_DETAIL_SUCCESS = "COLLEGE_DETAIL_SUCCESS";
export const COLLEGE_DETAIL_FAIL = "COLLEGE_DETAIL_FAIL";
export const COLLEGE_LIST_SUCCESS = "COLLEGE_LIST_SUCCESS";
export const COLLEGE_LIST_FAIL = "COLLEGE_LIST_FAIL";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SIMILAR_COLLEGES_LIST_SUCCESS = "SIMILAR_COLLEGES_LIST_SUCCESS";
export const SIMILAR_COLLEGES_LIST_FAIL = "SIMILAR_COLLEGES_LIST_FAIL";
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const STATE_COMPARISON_DATA_SUCCESS = "STATE_COMPARISON_DATA_SUCCESS";
export const STATE_COMPARISON_DATA_FAIL = "STATE_COMPARISON_DATA_FAIL";
export const COURSE_COMPARISON_DATA_SUCCESS = "COURSE_COMPARISON_DATA_SUCCESS";
export const COURSE_COMPARISON_DATA_FAIL = "COURSE_COMPARISON_DATA_FAIL";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL";
export const STATE_LIST_SUCCESS = "STATE_LIST_SUCCESS";
export const STATE_LIST_FAIL = "STATE_LIST_FAIL";
export const COURSE_LIST_SUCCESS = "COURSE_LIST_SUCCESS";
export const COURSE_LIST_FAIL = "COURSE_LIST_FAIL";
export const SET_DASHBOARD_INDEX = "SET_DASHBOARD_INDEX";